# Generated by Django 5.1.3 on 2024-11-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
