# Generated by Django 5.1.3 on 2024-11-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_skills_required_jobmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
