# Generated by Django 5.1.3 on 2024-11-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobmatch_score_alter_jobmatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='resume',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobs.resume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful'), ('pending', 'Pending')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
